---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/.yamllint .
  ansible-lint -x meta-incorrect,meta-no-info,package-latest
platforms:
  - name: instance-centos
    image: "spurin/diveintoansible:centos"
    privileged: true
    pre_build_image: true
    tty: true
    network_mode: "host"
  - name: instance-ubuntu
    image: "spurin/diveintoansible:ubuntu"
    privileged: true
    pre_build_image: true
    tty: true
    network_mode: "host"
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
