name: update collection

'on':
  push:
    branches:
      - main

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - name: retrieve collection code and update submodule
        run: |
          git clone --recursive https://github.com/louismichel100/ansible-collection-webapp.git
          cd ansible-collection-webapp
          git submodule update --init --recursive
          cd roles/webapp
          git pull origin main
          cd ../..
          git add .
          git config --global user.email "sangalamballamichel@gmail.com"
          git config --global user.name "louismichel100"
          git commit -m "update role nginx commit ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ANSIBLE_TOKEN }}
          branch: main
          directory: ansible-collection-webapp
          repository: louismichel100/ansible-collection-webapp
